services:
  database:
    image: postgres:16
    platform: linux/amd64
    restart: unless-stopped
    environment:
      - POSTGRES_DB=notifications-db
      - POSTGRES_USER=notifications-user
      - POSTGRES_PASSWORD=notifications-db-password
    ports:
      - 5432:5432
    volumes:
      - database-data:/var/lib/postgresql/data
    networks:
      - app_network

networks:
  app_network:
    external: false

volumes:
  database-data:
